project_id = "xhxvnpwrzghycrlzglbn"

[functions.send-verification-email]
verify_jwt = false

[functions.send-member-email]
verify_jwt = false

[functions.send-waitlist-confirmation]
verify_jwt = false

[functions.send-unsubscribe-confirmation]
verify_jwt = false
